### ISSUE TITLE
UI Language change

### ISSUE THREAD

**Issue by MagikarpBest** [rayshift/translatefgo#40]
Can you change UI language? Is it possible

**Comment by MagikarpBest** [comment]
@neobenedict

**Comment by deskm** [comment]
That would be harder than just modifying cached scripts. I've been playing this game since launch and I still get confused with the concurrent Option and My Room changes. So many useful UI changes that it's hard to keep track of it all. At the very least, translating just the Options menu would be useful. But again, that's not cached information I think.

**Comment by neobenedict** [comment]
It's not part of the cached data and thus not possible through this app.
